import styles from '@/scss/index.scss'
import Head from 'next/head'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <body>
            {children}
          </body>
        </html>
        )
}
